name: check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: golang:1.17
    steps:
    - uses: actions/checkout@v2
    - run: make
